// auto generated by go tool dist

package sys

const DefaultGoroot = `/Users/konkers/play/u-prebuilts/_build/go/darwin-x86_64/go`
const TheVersion = `go1.7.5`
const Goexperiment = ``
const StackGuardMultiplier = 1

